let associationPeerId=null;
function associationPeerBand(n){return n<50000?'0–49,999':n<100000?'50,000–99,999':n<200000?'100,000–199,999':'200,000+';}
function associationInsightRows(scopeName){
 const scope=MEMBERSHIP_ASSOCIATION_DATA.scopes[scopeName],juniors=new Map(scope.junior.map(r=>[r.id,r.memberships])),clubs=new Map();
 for(const c of MEMBERSHIP_CLUB_DATA.clubs){if((scopeName!=='all'&&c.scope!==scopeName)||!c[membershipPopulation])continue;const v=clubs.get(c.association)||{juniorHeavyClubs:0};if(c.junior*2>=c.all)v.juniorHeavyClubs++;clubs.set(c.association,v);}
 return scope[membershipPopulation].map(r=>({...r,juniorCount:juniors.get(r.id)||0,juniorHeavyClubs:clubs.get(r.id)?.juniorHeavyClubs||0}));
}
function associationInsightDefinitions(){return [
 {key:'female',label:'Female membership share',group:'Membership Mix',unit:'percent',count:r=>Math.round(r.femalePct*r.memberships),denom:r=>r.memberships},
 ...(membershipPopulation==='all'?[{key:'junior',label:'Junior membership share',group:'Membership Mix',unit:'percent',count:r=>r.juniorCount,denom:r=>r.memberships}]:[]),
 {key:'gc',label:'GC membership share',group:'Membership Mix',unit:'percent',count:r=>r.gcMemberships,denom:r=>r.memberships},
 {key:'public',label:'Public membership share',group:'Membership Mix',unit:'percent',count:r=>Math.round(r.publicMembersPct*r.memberships),denom:r=>r.memberships},
 {key:'clubSize',label:'Average memberships per club',group:'Clubs',unit:'number',count:r=>r.memberships,denom:r=>r.clubCount},
 {key:'publicClubs',label:'Public-club share',group:'Clubs',unit:'percent',count:r=>Math.round(r.publicClubsPct*r.clubCount),denom:r=>r.clubCount},
 {key:'juniorClubs',label:'Clubs with 50% or more juniors',group:'Clubs',unit:'percent',count:r=>r.juniorHeavyClubs,denom:r=>r.clubCount},
 {key:'age',label:'Average known age',group:'Age',unit:'years',count:r=>r.averageAge===null?0:r.averageAge*r.ageKnownCount,denom:r=>r.ageKnownCount},
 {key:'under25',label:'Memberships under age 25',group:'Age',unit:'percent',count:r=>r.under25Count,denom:r=>r.ageKnownCount},
 {key:'age65Plus',label:'Memberships age 65+',group:'Age',unit:'percent',count:r=>r.age65PlusCount,denom:r=>r.ageKnownCount}
];}
function associationMetricAggregate(def,rows){const count=rows.reduce((n,r)=>n+def.count(r),0),total=rows.reduce((n,r)=>n+def.denom(r),0);return {count,total,value:total?count/total:null};}
function associationMetricValue(def,value){return value===null?'—':def.unit==='percent'?pct(value):def.unit==='years'?`${value.toFixed(1)} years`:value.toLocaleString('en-US',{maximumFractionDigits:1});}
function associationMetricDifference(def,value,benchmark,label){if(value===null||benchmark===null)return 'Comparison unavailable';const delta=value-benchmark,scaled=def.unit==='percent'?delta*100:delta,units=def.unit==='percent'?'percentage points':def.unit==='years'?'years':'memberships per club';return Math.abs(scaled)<.05?`In line with ${label}`:`${Math.abs(scaled).toFixed(1)} ${units} ${delta>0?'above':'below'} ${label}`;}
function associationPeerComparison(){
 const scope=MEMBERSHIP_ASSOCIATION_DATA.scopes[membershipGeography],base=[...scope.all].sort((a,b)=>a.name.localeCompare(b.name)),selected=base.find(r=>r.id===associationPeerId);
 if(!selected)return null;
 const rows=associationInsightRows(membershipGeography),population=new Map(rows.map(r=>[r.id,r])),band=associationPeerBand(selected.activeGolfers),member=population.get(selected.id),peers=base.filter(r=>r.id!==selected.id&&r.region===selected.region&&associationPeerBand(r.activeGolfers)===band&&population.get(r.id)?.memberships>0).map(r=>({...population.get(r.id),allGolfers:r.activeGolfers})),national=associationInsightRows('aga');
 const metrics=associationInsightDefinitions().map(def=>{const a=associationMetricAggregate(def,member?[member]:[]),p=associationMetricAggregate(def,peers),n=associationMetricAggregate(def,national);return {...def,share:a.value,peerShare:p.value,nationalShare:n.value,selectedCount:a.count,peerCount:p.count,nationalCount:n.count,selectedBase:a.total,peerBase:p.total,nationalBase:n.total,difference:a.value!==null&&p.value!==null?(a.value-p.value)*(def.unit==='percent'?100:1):null};});
 return {base,selected,band,member,peers,metrics,peerTotal:peers.reduce((n,r)=>n+r.memberships,0)};
}
function associationInsightSelector(base,selected=null,extra=''){return `<div class="association-peer-controls"><label>Association<select aria-label="Compare association" onchange="associationPeerId=this.value||null;render()"><option value=""${!selected?' selected':''}>All Associations · Standouts</option>${base.map(r=>`<option value="${esc(r.id)}"${r.id===selected?.id?' selected':''}>${esc(r.name)}</option>`).join('')}</select></label>${extra}</div>`;}
function associationInsightQuantile(values,q){const position=(values.length-1)*q,lo=Math.floor(position);return values[lo]+(values[Math.ceil(position)]-values[lo])*(position-lo);}
function associationStandoutData(){
 const rows=associationInsightRows(membershipGeography),national=associationInsightRows('aga');
 return associationInsightDefinitions().map(def=>{
  const benchmark=associationMetricAggregate(def,national),eligible=rows.filter(r=>r.memberships>=1000&&def.denom(r)>0&&(def.group!=='Clubs'||r.clubCount>=10)&&(def.group!=='Age'||r.ageKnownCount>=100));
  const values=eligible.map(r=>({...r,value:def.count(r)/def.denom(r)})),sorted=values.map(r=>r.value).sort((a,b)=>a-b),q1=sorted.length?associationInsightQuantile(sorted,.25):0,q3=sorted.length?associationInsightQuantile(sorted,.75):0,iqr=q3-q1,low=q1-1.5*iqr,high=q3+1.5*iqr;
  const outliers=values.length>=4?values.filter(r=>r.value<low||r.value>high):[],candidates=outliers.length?outliers:values;
  const ranked=[...candidates].sort((a,b)=>Math.abs(b.value-(benchmark.value??0))-Math.abs(a.value-(benchmark.value??0))||a.name.localeCompare(b.name));
  return {...def,benchmark,eligible:eligible.length,outlierCount:outliers.length,featured:ranked.slice(0,3),low,high};
 });
}
function associationInsightMethods(){return `<details class="chart-data-disclosure association-peer-data"><summary><span class="chart-data-show">How comparisons are calculated</span><span class="chart-data-hide">Hide methodology</span></summary><p class="live-source-note">The national benchmark combines all AGA associations, regardless of region or size, and includes the selected association when it is an AGA. Member filters apply throughout. Overview eligibility: at least 1,000 selected memberships; club insights also require at least 10 clubs, and age insights require at least 100 memberships with known ages. Outliers are values beyond 1.5 times the interquartile range below the first quartile or above the third quartile among eligible associations in the selected geography (at least four required). Up to three outliers are shown, ranked by absolute difference from the national benchmark. Where no outliers qualify, the three largest benchmark gaps are shown instead. These are descriptive differences, not performance ratings.</p><p class="live-source-note">Membership shares count memberships, including multiple memberships held by one golfer; unknown gender and access remain in the denominator. GC memberships are included in Public. Age measures use only valid known ages (0–120), weighted by membership counts; unknown ages are excluded. Club measures cover clubs with active memberships in the selected population. Junior-heavy clubs use their all-member junior share regardless of the selected population. Average club size is memberships divided by clubs. Peer groups match region and all-member unique-golfer size band, excluding the selected association; benchmarks use summed numerators divided by summed denominators. Snapshot: ${membershipScopeDate()}.</p></details>`;}
function associationStandouts(base){const insights=associationStandoutData();return `<section class="association-peer-insights" aria-label="Association standouts">${associationInsightSelector(base)}${['Membership Mix','Clubs','Age'].map(group=>`<section class="association-insight-section"><h2>${group}</h2><div class="association-peer-grid">${insights.filter(d=>d.group===group).map(d=>`<article class="association-peer-card association-standout-card" data-standout-metric="${d.key}"><h3>${d.label}</h3><div class="association-standout-benchmark"><span>National Benchmark</span><strong>${associationMetricValue(d,d.benchmark.value)}</strong></div><div class="association-standout-caption">${d.outlierCount?`${d.outlierCount} ${d.outlierCount===1?'outlier':'outliers'} · ${d.featured.length} shown`:d.eligible<4?'Largest gaps · too few associations to assess outliers':'Largest gaps · no statistical outliers'} · ${d.eligible} eligible associations</div><div>${d.featured.map(r=>`<div class="association-standout-row" data-standout-association="${esc(r.id)}"><div><button type="button" onclick="associationPeerId='${esc(r.id)}';render()">${esc(r.name)}</button><strong>${associationMetricValue(d,r.value)}</strong></div><p>${associationMetricDifference(d,r.value,d.benchmark.value,'national')}</p><small>${d.group==='Age'?`${fmt(r.ageKnownCount)} known-age memberships · ${pct(r.ageKnownCount/r.memberships)} age coverage`:d.group==='Clubs'?`${fmt(r.clubCount)} clubs · ${fmt(r.memberships)} memberships`:`${fmt(r.memberships)} memberships`}</small></div>`).join('')||'<p>No associations meet the minimum sample size for this measure.</p>'}</div></article>`).join('')}</div></section>`).join('')}${associationInsightMethods()}</section>`;}
function associationInsights(){
 const base=[...MEMBERSHIP_ASSOCIATION_DATA.scopes[membershipGeography].all].sort((a,b)=>a.name.localeCompare(b.name));
 if(!base.some(r=>r.id===associationPeerId))associationPeerId=null;
 if(!associationPeerId)return associationStandouts(base);
 const {selected,band,member,peers,metrics}=associationPeerComparison();
 const line=(m,value,label)=>{const max=m.unit==='percent'?1:Math.max(m.share||0,m.peerShare||0,m.nationalShare||0,1)*1.2;return `<div class="association-comparison"><div class="association-comparison-label"><strong>${label} comparison</strong><span>${associationMetricDifference(m,m.share,value,label==='Peer'?'peers':'national')}</span></div>${m.share===null||value===null?'<p>Comparison unavailable</p>':`<div class="association-comparison-axis" role="img" aria-label="${esc(selected.name)} ${associationMetricValue(m,m.share)}; ${label} benchmark ${associationMetricValue(m,value)}"><span class="association-comparison-join" style="left:${Math.min(m.share,value)/max*100}%;width:${Math.abs(m.share-value)/max*100}%"></span><i class="association-comparison-marker benchmark" style="left:${value/max*100}%"></i><i class="association-comparison-marker selected" style="left:${m.share/max*100}%"></i></div>`}</div>`;};
 return `<section class="association-peer-insights" aria-label="Association peer comparisons">${associationInsightSelector(base,selected,`<div><strong>${esc(selected.region)}</strong><span>${band} unique golfers · ${peers.length} ${peers.length===1?'peer association':'peer associations'}</span></div>`)}${!member?'<p class="association-peer-empty">This association has no active memberships in the selected group.</p>':''}${!peers.length?'<p class="association-peer-empty">No other associations in this region and size band have memberships in the selected group.</p>':''}${['Membership Mix','Clubs','Age'].map(group=>`<section class="association-insight-section"><h2>${group}</h2><div class="association-peer-grid">${metrics.filter(m=>m.group===group).map(m=>`<article class="association-peer-card" data-peer-metric="${m.key}" data-selected-share="${m.share??''}" data-peer-share="${m.peerShare??''}" data-national-share="${m.nationalShare??''}"><h3>${m.label}</h3><div class="association-peer-values"><div><span>${esc(selected.name)}</span><strong>${associationMetricValue(m,m.share)}</strong></div><div><span>Peer Benchmark</span><strong>${associationMetricValue(m,m.peerShare)}</strong></div><div><span>National Benchmark</span><strong>${associationMetricValue(m,m.nationalShare)}</strong></div></div>${line(m,m.peerShare,'Peer')}${line(m,m.nationalShare,'National')}<div class="association-comparison-key"><span><i class="selected"></i>${esc(selected.name)}</span><span><i class="benchmark"></i>Benchmark</span><span>${m.unit==='percent'?'0–100% scale':'Shared scale for both comparisons'}</span></div>${m.group==='Age'&&member?`<p class="association-age-coverage">${fmt(member.ageKnownCount)} known-age memberships · ${pct(member.ageKnownCount/member.memberships)} age coverage</p>`:''}</article>`).join('')}</div></section>`).join('')}<details class="chart-data-disclosure association-peer-data"><summary><span class="chart-data-show">Show data &amp; peers</span><span class="chart-data-hide">Hide data &amp; peers</span></summary><div class="chart-data-table-wrap"><table><caption>Comparison denominators</caption><thead><tr><th>Measure</th><th>${esc(selected.name)}</th><th>Peer group</th><th>National</th></tr></thead><tbody>${metrics.map(m=>`<tr><th>${m.label}</th><td>${fmt(m.selectedBase)}</td><td>${fmt(m.peerBase)}</td><td>${fmt(m.nationalBase)}</td></tr>`).join('')}</tbody></table><table><caption>Peer associations · selected association excluded</caption><thead><tr><th>Association</th><th>All-member unique golfers</th><th>Selected memberships</th></tr></thead><tbody>${peers.map(r=>`<tr data-peer-association="${esc(r.id)}"><th>${esc(r.name)}</th><td>${fmt(r.allGolfers)}</td><td>${fmt(r.memberships)}</td></tr>`).join('')||'<tr><td colspan="3">No eligible peers.</td></tr>'}</tbody></table></div></details>${associationInsightMethods()}</section>`;
}
