const {chromium}=require('/Users/EvanBelfi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/Handicapping%20and%20GHIN%20Dashboard.html');await page.locator('[data-top="membership"]').click();await page.locator('[data-sub="composition"]').click();await page.locator('[data-membership-population="all"]').click();
const read=()=>page.evaluate(()=>{const r=membershipExplorerResult();return {total:r.total,unique:r.unique,nh:r.nh,additional:r.additional,sum:r.groups.reduce((n,g)=>n+g.total,0)}});
assert.deepEqual(await read(),{total:3840678,unique:3544477,nh:438165,additional:296201,sum:3840678});
assert(await page.locator('.membership-live .composition-card').last().evaluate(el=>el.classList.contains('membership-explorer')));
for(const group of ['membershipType','association','access','clubGroup','clubType','gender','age','handicap','club']){await page.selectOption('#meGroupBy',group);assert.equal((await read()).sum,3840678);}
const add=async(key,value)=>{await page.selectOption('#meFilterDimension',key);await page.selectOption('#meFilterValue',value);await page.locator('[data-me-add]').click();};
await add('handicap','No Index');assert.equal((await read()).total,438165);assert.equal((await read()).unique,433444);await page.locator('[data-me-clear]').click();
for(const pair of [['membershipType','Junior'],['association','53'],['gender','Female'],['clubGroup','Affiliate / WORE']])await add(...pair);
assert.equal((await read()).total,8728);await add('handicap','No Index');assert.equal((await read()).total,7853);assert.equal((await read()).unique,7730);await page.locator('[data-me-remove="handicap"]').click();assert.equal((await read()).total,8728);await page.locator('[data-me-clear]').click();
for(const [pop,total,unique] of [['regular',3427469,3152507],['junior',396381,382706]]){await page.locator(`[data-membership-population="${pop}"]`).click();assert.equal((await read()).total,total);assert.equal((await read()).unique,unique);}
await add('membershipType','Regular');assert.equal((await read()).total,0);await page.locator('[data-me-clear]').click();await page.locator('[data-membership-population="all"]').click();await page.selectOption('#meGroupBy','membershipType');await page.locator('.membership-explorer').screenshot({path:'reports/membership-explorer-preview.png'});await page.setViewportSize({width:390,height:844});assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)));assert.deepEqual(errors,[]);console.log('Membership Explorer totals, unique counts, 9 groupings, stacked filters, NH reconciliation, population changes and mobile passed.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
