function liveGhinMonths(kind='gps'){return Array.from({length:kind==='trials'?GHIN_LIVE_DATA.trialReportMonth:GHIN_LIVE_DATA.reportMonth},(_,i)=>`${GHIN_LIVE_DATA.year}-${String(i+1).padStart(2,'0')}-01`);}
function liveGhinSeries(kind){return kind==='trials'?[{label:'Trials Created',key:'Trial record created',color:'#a9bdd2'},{label:'Recorded Conversions',key:'Sign-up recorded',color:'#173d66'}]:[{label:'New Subscribe',key:'new',color:'#a9bdd2'},{label:'Renewed Subscribe',key:'renewed',color:'#173d66'}];}
function liveGhinValue(kind,key,month){const d=GHIN_LIVE_DATA;return kind==='trials'?(d.trials.find(r=>r.event_type===key&&r.event_month===month)?.trial_records||0):(d.gps.find(r=>r.activity_status===key&&r.activity_month===month)?.activity_records||0);}
function liveGhinKpiChange(value,prior){if(!prior)return '';const delta=(value/prior-1)*100;return `<em class="home-ghin-kpi-change ${delta<0?'negative':'positive'}" title="Change vs January–September 2025" aria-label="${delta<0?'Down':'Up'} ${Math.abs(delta).toFixed(1)} percent versus 2025 YTD">${delta<0?'▼':'▲'} ${Math.abs(delta).toFixed(1)}%</em>`;}
function liveGhinKpis(items){return `<div class="home-score-kpis live-ghin-kpis">${items.map(([label,value,change])=>`<div><span>${label}</span><div class="home-ghin-kpi-number"><strong>${value}</strong>${change||''}</div></div>`).join('')}</div>`;}
function liveGhinBars(kind,showValues=false){const months=liveGhinMonths(kind),series=liveGhinSeries(kind),w=650,h=370,l=60,r=20,t=35,b=65,max=Math.max(1,...months.flatMap(m=>series.map(s=>liveGhinValue(kind,s.key,m))))*1.18,width=(w-l-r)/months.length,y=n=>h-b-(h-t-b)*n/max;let svg=Array.from({length:5},(_,i)=>{const n=max*i/4;return `<line class="gridline" x1="${l}" x2="${w-r}" y1="${y(n)}" y2="${y(n)}"/><text class="axis-label" x="${l-10}" y="${y(n)+5}" text-anchor="end">${short(n)}</text>`;}).join('');months.forEach((month,i)=>{series.forEach((s,j)=>{const n=liveGhinValue(kind,s.key,month);svg+=`<rect x="${l+i*width+width*.17+j*width*.34}" y="${y(n)}" width="${width*.29}" height="${h-b-y(n)}" fill="${s.color}" rx="2" data-ghin-month="${month}" data-ghin-series="${s.key}" data-ghin-count="${n}"><title>${s.label} · ${month.slice(0,7)}: ${fmt(n)}</title></rect>${showValues?`<text class="trial-month-value" x="${l+i*width+width*.17+j*width*.34+width*.145}" y="${y(n)-9}" text-anchor="middle">${fmt(n)}</text>`:''}`;});svg+=`<text class="axis-label" x="${l+(i+.5)*width}" y="${h-b+25}" text-anchor="middle">${['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'][i]}</text>`;});return `<div class="live-ghin-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${kind==='trials'?'Trials created and recorded conversions':'GPS new and renewed subscribe records'}, January–${kind==='trials'?'September':'August'} 2026">${svg}</svg><div class="live-ghin-legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${s.label}</span>`).join('')}</div></div>`;}
function liveGhinDisclosure(kind){const trial=kind==='trials',series=liveGhinSeries(kind),rows=liveGhinMonths(kind).map(month=>`<tr><th>${month.slice(0,7)}</th>${series.map(s=>`<td>${fmt(liveGhinValue(kind,s.key,month))}</td>`).join('')}</tr>`).join('');return `<details class="chart-data-disclosure live-ghin-data"><summary><span class="chart-data-show">Show data</span><span class="chart-data-hide">Hide data</span></summary><div class="chart-data-table-wrap"><table><caption>January–${trial?'September':'August'} 2026</caption><thead><tr><th>Month</th>${series.map(s=>`<th>${s.label}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div><p class="live-source-note">${trial?'Created counts use trial_golfers.created_at; recorded conversions use sign_up_date. Conversions in a month may come from trials created in earlier months, so dividing the two is not a cohort conversion rate. July and August conversion counts match the supplied Tableau report.':'Bars count gps_activities records labeled new and renewed, grouped by created_at; they are not unique subscriber counts, verified payments, or historical active-subscriber totals. Subscribe statuses can be updated after creation. The October 2 snapshot contains 100,105 unique golfers with an active subscription flag: 99,703 with at least one current date range, 194 with all date ranges outside the current period, and 208 with missing dates and no confirmed current range. Current dates and active flags do not establish paid subscription status. Canceled records with current dates are retained.'} Extracted October 2, 2026. The current partial month is excluded from these charts.</p></details>`;}
function liveGhinProductCard(kind,home=true){const trial=kind==='trials',series=liveGhinSeries(kind),totals=series.map(s=>liveGhinMonths(kind).reduce((n,m)=>n+liveGhinValue(kind,s.key,m),0)),snapshot=GHIN_LIVE_DATA.gpsSnapshot,items=trial?[[`YTD Trials Created`,fmt(totals[0])],[`YTD Recorded Conversions`,fmt(totals[1])]]:[['Active-Flagged Golfers · Oct 2',fmt(snapshot.activeFlagged)],['Current-Date Coverage · Oct 2',fmt(snapshot.currentDates)]];return `<article class="card ${home?'half':''} live-ghin-product" data-live-ghin="${kind}"><div class="scores-card-band has-toggle"><span>${trial?'GHIN Trials · Jan–Sep 2026':'Advanced GPS · Subscription Subscribe'}</span>${home?`<button type="button" class="trend-title-link" data-open-ghin-sub="${trial?'ghin-trials':'advanced-gps'}">Open ${trial?'GHIN Trials':'Advanced GPS'} →</button>`:''}</div>${liveGhinKpis(items)}${!trial?'<h3 class="live-ghin-chart-title">New &amp; Renewed Subscribe · Jan–Aug 2026</h3>':''}${liveGhinBars(kind)}${liveGhinDisclosure(kind)}</article>`;}
function summaryGpsCard(){
 const years=[2024,2025,2026],series=[{key:'newCount',label:'New Subscribers',color:'#a9bdd2'},{key:'renewed',label:'Renewals',color:'#173d66'}],source=gpsTrendRows().filter(r=>r.index<9),rows=years.map(year=>({year,...Object.fromEntries(series.map(s=>[s.key,source.filter(r=>r.year===year).reduce((n,r)=>n+r[s.key],0)]))})),w=650,h=370,l=58,r=20,t=38,b=57,max=Math.ceil(Math.max(...rows.flatMap(row=>series.map(s=>row[s.key])))*1.2/10000)*10000,y=n=>h-b-n/max*(h-t-b),center=i=>l+(i+.5)*(w-l-r)/3;
 let svg=Array.from({length:5},(_,i)=>{const n=max*i/4;return `<line class="gridline" x1="${l}" x2="${w-r}" y1="${y(n)}" y2="${y(n)}"/><text class="axis-label" x="${l-10}" y="${y(n)+4}" text-anchor="end">${short(n)}</text>`;}).join('');
 rows.forEach((row,i)=>{const c=center(i);series.forEach((s,j)=>{const value=row[s.key],cx=c+(j?29:-29),prior=rows[i-1]?.[s.key],delta=prior?(value/prior-1)*100:null;svg+=`<g class="trial-rate-point" tabindex="0" role="button" aria-label="${row.year} January–September ${s.label}: ${fmt(value)}" data-period="${row.year} · Jan–Sep" data-metric="${s.label}" data-total="${fmt(value)}" onpointerenter="showGpsTrendTooltip(this)" onpointerleave="hideGpsTrendTooltip(this)" onfocus="showGpsTrendTooltip(this)" onblur="hideGpsTrendTooltip(this)" onclick="showGpsTrendTooltip(this)"><rect x="${cx-24}" y="${y(value)}" width="48" height="${h-b-y(value)}" rx="4" fill="${s.color}"/><text class="home-gps-value" x="${cx}" y="${y(value)-10}" text-anchor="middle">${fmt(value)}</text>${delta===null?'':`<text class="home-gps-change" x="${cx}" y="${y(value)-27}" text-anchor="middle" fill="${delta>=0?'#07853b':'#c5232c'}">${delta>=0?'▲':'▼'} ${Math.abs(delta).toFixed(1)}%</text>`}</g>`;});svg+=`<text class="axis-label" x="${c}" y="${h-b+24}" text-anchor="middle">${row.year}</text><text class="axis-label" x="${c}" y="${h-b+43}" text-anchor="middle">Jan–Sep</text>`;});
 return `<article class="card half live-ghin-product home-gps-ytd" data-live-ghin="gps"><div class="scores-card-band has-toggle"><span>Advanced GPS Subscriptions</span><button type="button" class="trend-title-link" data-open-ghin-sub="advanced-gps">Open Advanced GPS →</button></div>${liveGhinKpis([['2026 YTD New Subscribers',fmt(rows[2].newCount),liveGhinKpiChange(rows[2].newCount,rows[1].newCount)],['2026 YTD Renewals',fmt(rows[2].renewed),liveGhinKpiChange(rows[2].renewed,rows[1].renewed)]])}<div class="live-ghin-chart trial-rate-chart gps-trend-chart"><div class="trial-rate-tooltip" role="tooltip" hidden></div><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="New GPS subscribers and renewals, January–September 2024, 2025, and 2026">${svg}</svg><div class="live-ghin-legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${s.label}</span>`).join('')}</div></div>${trialDataDisclosure(['Year · Jan–Sep','New Subscribers','Renewals'],rows.map(row=>[row.year,fmt(row.newCount),fmt(row.renewed)]),'January–September totals for each year, using the same data as the Advanced GPS charts. Percentage labels compare each category with the prior year over the same months. Counts use new and renewed GPS records grouped by creation month; they are not historical active-subscriber counts or verified payments. Extracted October 2, 2026.')}</article>`;
}

function summaryTrialsCard(){return liveGhinProductCard('trials');}
function summaryTrialConversionsCard(){const months=liveGhinMonths('trials'),created=months.reduce((n,m)=>n+liveGhinValue('trials','Trial record created',m),0),converted=months.reduce((n,m)=>n+liveGhinValue('trials','Sign-up recorded',m),0);return trialMetricCard('converted').replace('All GHIN Trial Conversions by Year','GHIN Trials').replace('class="card live-ghin-product trial-detail-card"','class="card half live-ghin-product trial-detail-card home-trial-conversions"').replace(/<h3>(.*?)<span class="trial-year-toggle"([\s\S]*?)<\/span><\/h3>/, '<div class="scores-card-band has-toggle"><span>$1</span><button type="button" class="trend-title-link" data-open-ghin-sub="ghin-trials">Open GHIN Trials →</button></div><div class="home-trial-view-controls"><span class="trial-year-toggle"$2</span></div>').replace('<div class="home-trial-view-controls">',liveGhinKpis([['2026 YTD Trials Created',fmt(created),liveGhinKpiChange(created,months.reduce((n,m)=>n+liveGhinValue('trials','Trial record created',m.replace('2026','2025')),0))],['2026 YTD Conversions',fmt(converted),liveGhinKpiChange(converted,months.reduce((n,m)=>n+liveGhinValue('trials','Sign-up recorded',m.replace('2026','2025')),0))]])+'<div class="home-trial-view-controls">');}
function trialDataDisclosure(headers,rows,note){const widths=headers.length===5?[12,26,21,21,20]:headers.length===3?[46,29,25]:[70,30];return `<details class="chart-data-disclosure live-ghin-data trial-clean-data"><summary><span class="chart-data-show">Show data</span><span class="chart-data-hide">Hide data</span></summary><div class="chart-data-table-wrap"><table class="trial-data-table"><colgroup>${widths.map(w=>`<col style="width:${w}%">`).join('')}</colgroup><thead><tr>${headers.map((x,i)=>`<th scope="col" class="${i===0||(headers.length===5&&i===1)?'trial-text-col':'trial-number-col'}">${x==='Trials Created'?'Trials<br>Created':x==='Conversion Rate'?'Conversion<br>Rate':x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>`<${i===0?'th scope="row"':'td'} class="${i===0||(headers.length===5&&i===1)?'trial-text-col':'trial-number-col'}">${x}</${i===0?'th':'td'}>`).join('')}</tr>`).join('')}</tbody></table></div><details class="trial-methodology"><summary>Definitions &amp; reporting notes</summary><p class="live-source-note">${note}</p></details></details>`;}

function trialPanel(title,body,details){return `<article class="card live-ghin-product trial-detail-card"><h3>${title}</h3>${body}${details}</article>`;}
const trialMetricModes={created:'ytd',converted:'ytd',rate:'ytd'};
const trialMetricYears={created:new Set([2024,2025,2026]),converted:new Set([2024,2025,2026]),rate:new Set([2024,2025,2026])};
function setTrialMetricMode(kind,mode){trialMetricModes[kind]=['ytd','annual','monthly'].includes(mode)?mode:'ytd';render();document.querySelector(`[data-trial-metric-mode="${kind}-${mode}"]`)?.focus({preventScroll:true});}
function toggleTrialMetricYear(kind,year){const selected=trialMetricYears[kind];selected.has(year)?selected.delete(year):selected.add(year);render();document.querySelector(`[data-trial-metric-year="${kind}-${year}"]`)?.focus({preventScroll:true});}
function trialMetricChange(rows,v,kind,mode,x,y){
 if(mode!=='ytd'||v.year!==2026)return '';
 const prior=rows.find(r=>r.year===v.year-1),value=r=>kind==='rate'?r.rate:r[kind],base=value(prior);if(!base)return '';
 const delta=(value(v)/base-1)*100;
 return `<text class="trial-change-label" data-trial-change="${v.year}" x="${x}" y="${y}" text-anchor="middle" fill="${delta>=0?'#07853b':'#c5232c'}">${delta>=0?'▲':'▼'} ${Math.abs(delta).toFixed(1)}%<title>January–September 2026 vs January–September 2025; relative percentage change</title></text>`;
}
function showTrialRateTooltip(point){
 const chart=point.closest('.trial-rate-chart'),tip=chart.querySelector('.trial-rate-tooltip'),d=point.dataset;
 tip.innerHTML=`<strong>${d.period}</strong><div>Conversion rate <b>${pct(Number(d.rate))}</b></div><div>Trials created <b>${fmt(Number(d.created))}</b></div><div>Conversions <b>${fmt(Number(d.converted))}</b></div>`;
 tip.hidden=false;const box=chart.getBoundingClientRect(),target=point.getBoundingClientRect();
 tip.style.left=Math.max(8,Math.min(target.left-box.left+target.width/2-tip.offsetWidth/2,chart.clientWidth-tip.offsetWidth-8))+'px';
 const above=target.top-box.top-tip.offsetHeight-10;tip.style.top=(above>=0?above:target.bottom-box.top+10)+'px';
}
function hideTrialRateTooltip(point){point.closest('.trial-rate-chart').querySelector('.trial-rate-tooltip').hidden=true;}
function trialMetricCard(kind){
 const mode=trialMetricModes[kind],selected=trialMetricYears[kind],title={created:'All GHIN Trials Created by Year',converted:'All GHIN Trial Conversions by Year',rate:'Conversion Rate'}[kind],metric=v=>kind==='rate'?v.rate:v[kind],format=n=>kind==='rate'?pct(n):fmt(n);
 const years=[2024,2025,2026],colors=['#8496ad','#5585ad','#173d66'],months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],rows=years.flatMap((year,yi)=>months.flatMap((month,i)=>{const date=`${year}-${String(i+1).padStart(2,'0')}-01`,created=GHIN_LIVE_DATA.trials.find(r=>r.event_type==='Trial record created'&&r.event_month===date),converted=GHIN_LIVE_DATA.trials.find(r=>r.event_type==='Sign-up recorded'&&r.event_month===date);return (year!==GHIN_LIVE_DATA.year||i<GHIN_LIVE_DATA.trialReportMonth)&&created&&converted&&created.trial_records>0?[{year,month,i,created:created.trial_records,converted:converted.trial_records,rate:converted.trial_records/created.trial_records,color:colors[yi]}]:[];}));
 const w=650,h=350,l=58,r=25,t=25,b=50,x=i=>l+i*(w-l-r)/11;let ceiling=kind==='rate'?Math.max(1,...rows.map(v=>v.rate)):Math.max(1,...rows.map(v=>metric(v)))*1.25;const y=n=>h-b-n/ceiling*(h-t-b);
 let svg=Array.from({length:5},(_,i)=>{const n=ceiling*i/4;return `<line class="gridline" x1="${l}" x2="${w-r}" y1="${y(n)}" y2="${y(n)}"/><text class="axis-label" x="${l-10}" y="${y(n)+4}" text-anchor="end">${kind==='rate'?pct(n):short(n)}</text>`;}).join('')+months.map((m,i)=>`<text class="axis-label" x="${x(i)}" y="${h-b+28}" text-anchor="middle">${m}</text>`).join('');
 years.filter(year=>selected.has(year)).forEach(year=>{const points=rows.filter(v=>v.year===year);svg+=`<g data-trial-rate-series="${year}"><polyline points="${points.map(v=>`${x(v.i)},${y(metric(v))}`).join(' ')}" fill="none" stroke="${points[0].color}" stroke-width="${year===2026?3.5:2.5}"/>${points.map(v=>{const label=`${year} ${v.month}: ${pct(v.rate)} · ${fmt(v.created)} trials created · ${fmt(v.converted)} conversions`;return `<g class="trial-rate-point" tabindex="0" role="button" aria-label="${label}" data-period="${v.month} ${year}" data-created="${v.created}" data-converted="${v.converted}" data-rate="${v.rate}" onpointerenter="showTrialRateTooltip(this)" onpointerleave="hideTrialRateTooltip(this)" onfocus="showTrialRateTooltip(this)" onblur="hideTrialRateTooltip(this)" onclick="showTrialRateTooltip(this)" onkeydown="if(event.key==='Escape')hideTrialRateTooltip(this)"><circle cx="${x(v.i)}" cy="${y(metric(v))}" r="12" fill="transparent"/><circle cx="${x(v.i)}" cy="${y(metric(v))}" r="5" fill="white" stroke="${v.color}" stroke-width="2" pointer-events="none"/></g>`;}).join('')}</g>`;});
 const annualRows=years.map((year,i)=>{const records=rows.filter(v=>v.year===year&&(mode!=='ytd'||v.i<GHIN_LIVE_DATA.trialReportMonth)),created=records.reduce((n,v)=>n+v.created,0),converted=records.reduce((n,v)=>n+v.converted,0);return {year,month:mode==='ytd'?(year===2024?'Jun–Sep (partial)':'Jan–Sep'):(year===2024?'Jun–Dec (partial)':year===2025?'Full year':'Jan–Sep YTD'),created,converted,rate:converted/created,color:colors[i]};});
 if(mode!=='monthly'){
  if(kind!=='rate')ceiling=Math.max(1,...annualRows.map(metric))*1.25;
  svg=Array.from({length:5},(_,i)=>{const n=ceiling*i/4;return `<line class="gridline" x1="${l}" x2="${w-r}" y1="${y(n)}" y2="${y(n)}"/><text class="axis-label" x="${l-10}" y="${y(n)+4}" text-anchor="end">${kind==='rate'?pct(n):short(n)}</text>`;}).join('');
  annualRows.forEach((v,i)=>{const center=l+(i+.5)*(w-l-r)/3;svg+=`<text class="axis-label" x="${center}" y="${h-b+23}" text-anchor="middle">${v.year}</text><text class="axis-label" x="${center}" y="${h-b+42}" text-anchor="middle">${v.month}</text>`;if(!selected.has(v.year))return;
   svg+=`<g data-trial-rate-series="${v.year}" class="trial-rate-point" tabindex="0" role="button" aria-label="${v.year} ${v.month}: ${format(metric(v))}" data-period="${v.year} · ${v.month}" data-created="${v.created}" data-converted="${v.converted}" data-rate="${v.rate}" onpointerenter="showTrialRateTooltip(this)" onpointerleave="hideTrialRateTooltip(this)" onfocus="showTrialRateTooltip(this)" onblur="hideTrialRateTooltip(this)" onclick="showTrialRateTooltip(this)" onkeydown="if(event.key==='Escape')hideTrialRateTooltip(this)"><rect data-trial-metric-bar="${kind}-${v.year}" x="${center-48}" y="${y(metric(v))}" width="96" height="${h-b-y(metric(v))}" rx="5" fill="${v.color}"/><text class="trial-chart-value" x="${center}" y="${y(metric(v))-12}" text-anchor="middle">${format(metric(v))}</text>${trialMetricChange(annualRows,v,kind,mode,center,y(metric(v))-32)}</g>`;
  });
 }
 if(!selected.size)svg+=`<text x="${w/2}" y="${h/2}" text-anchor="middle" class="axis-label">Select a year to show its data.</text>`;
 const legend=`<div class="trial-rate-years" role="group" aria-label="Show or hide ${title} years">${years.map((year,i)=>`<button type="button" data-trial-metric-year="${kind}-${year}" aria-pressed="${selected.has(year)}" onclick="toggleTrialMetricYear('${kind}',${year})"><i style="background:${colors[i]}"></i>${year}</button>`).join('')}</div>`;
 return trialPanel(`${title} <span class="trial-year-toggle" role="group" aria-label="${title} chart view">${[['ytd','YTD'],['annual','Annual Totals'],['monthly','Monthly']].map(([view,label])=>`<button type="button" data-trial-metric-mode="${kind}-${view}" aria-pressed="${mode===view}" onclick="setTrialMetricMode('${kind}','${view}')">${label}</button>`).join('')}</span>`,`<div class="live-ghin-chart trial-rate-chart"><div class="trial-rate-tooltip" role="tooltip" hidden></div><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${title} · ${mode==='monthly'?'January through December':mode==='ytd'?'YTD':'Annual Totals'}">${svg}</svg>${legend}</div>`,trialDataDisclosure(['Year',mode!=='monthly'?'Period':'Month','Trials Created','Conversions','Conversion Rate'],(mode!=='monthly'?annualRows:rows).filter(v=>selected.has(v.year)).map(v=>[v.year,v.month,fmt(v.created),fmt(v.converted),pct(v.rate)]),'Created counts use created_at; conversions use sign_up_date. Conversion rate = total conversions divided by total trials created in the displayed period, not an average of monthly rates or a same-cohort conversion percentage. YTD uses January–September, with partial June–September history in 2024. Annual Totals uses June–December 2024, full-year 2025, and January–September 2026. Monthly shows all available complete months on a January–December axis. Percentage-change labels appear only when adjacent bars cover identical complete periods: 2026 vs 2025 in YTD. No change is shown for incomplete 2024 comparisons or full-year vs partial-year totals. Rate changes are relative percentages, not percentage points. Extracted October 2, 2026.'));
}

let trialHighlightMonth='all';
function trialHighlightMonthLabel(month){const [year,m]=month.split('-');return `${['January','February','March','April','May','June','July','August','September','October','November','December'][Number(m)-1]} ${year}${month==='2026-10-01'?' (through Oct 2)':month==='2024-06-01'?' (from Jun 6)':''}`;}
function trialHighlightValues(){
 const all=trialHighlightMonth==='all',total=field=>GHIN_LIVE_DATA.cohorts.reduce((n,r)=>n+r[field],0),monthly=event=>GHIN_LIVE_DATA.trials.find(r=>r.event_type===event&&r.event_month===trialHighlightMonth)?.trial_records;
 const created=all?total('trials_created'):monthly('Trial record created'),converted=all?total('recorded_conversions'):monthly('Sign-up recorded'),period=all?'All time · through Oct 2':trialHighlightMonthLabel(trialHighlightMonth);
 return [[all?'ALL TRIALS CREATED':'TRIALS CREATED',created==null?'—':fmt(created),period],[all?'ALL TRIAL CONVERSIONS':'TRIAL CONVERSIONS',converted==null?'—':fmt(converted),period],[all?'ALL TIME CONVERSION RATE':'CONVERSION RATE',created>0&&converted!=null?pct(converted/created):'—',period]];
}
function setTrialHighlightMonth(month){const valid=month==='all'||GHIN_LIVE_DATA.trials.some(r=>r.event_month===month);if(!valid)return;trialHighlightMonth=month;trialHighlightValues().forEach(([label,value,period],i)=>{const box=document.querySelectorAll('.trial-summary-kpis>div')[i];box.querySelector('span').textContent=label;box.querySelector('strong').textContent=value;box.querySelector('small').textContent=period;});}
function trialHighlightSelector(){const months=[...new Set(GHIN_LIVE_DATA.trials.map(r=>r.event_month))].sort().reverse();return `<div class="trial-highlight-filter"><label for="trial-highlight-month">Month</label><select id="trial-highlight-month" onchange="setTrialHighlightMonth(this.value)"><option value="all" ${trialHighlightMonth==='all'?'selected':''}>All time</option>${months.map(month=>`<option value="${month}" ${trialHighlightMonth===month?'selected':''}>${trialHighlightMonthLabel(month)}</option>`).join('')}</select></div>`;}
function trialDestinationPie(){
 const d=GHIN_LIVE_DATA.trialDestinations,total=d.gc+d.aga,angle=d.gc/total*Math.PI*2,cx=220,cy=220,r=205,endX=cx+r*Math.sin(angle),endY=cy-r*Math.cos(angle);
 const slice=`M ${cx} ${cy} L ${cx} ${cy-r} A ${r} ${r} 0 ${angle>Math.PI?1:0} 1 ${endX} ${endY} Z`,label=(start,end,name,value,color)=>{const mid=(start+end)/2,x=cx+Math.sin(mid)*r*.72,y=cy-Math.cos(mid)*r*.72;return `<text x="${x}" y="${y-8}" text-anchor="middle" fill="${color}" font-weight="700"><tspan x="${x}" font-size="15">${name}</tspan><tspan x="${x}" dy="24" font-size="23">${pct(value/total)}</tspan></text>`;};
 return trialPanel('YTD Trial Conversions by Destination',`<div class="live-ghin-chart trial-destination-pie"><svg viewBox="0 0 440 440" role="img" aria-label="${d.month}: ${fmt(d.gc)} GC Club conversions and ${fmt(d.aga)} AGA conversions"><circle cx="${cx}" cy="${cy}" r="${r}" fill="#a9bdd2"/><path d="${slice}" fill="#173d66"><title>GC Club Conversions: ${fmt(d.gc)} · ${pct(d.gc/total)}</title></path><circle cx="${cx}" cy="${cy}" r="82" fill="white"/><text x="${cx}" y="${cy-3}" text-anchor="middle" fill="#173d66" font-size="32" font-weight="800">${fmt(total)}<tspan baseline-shift="super" font-size="18">*</tspan></text><text x="${cx}" y="${cy+20}" text-anchor="middle" fill="#536b85" font-size="11" font-weight="700" letter-spacing="1">CONVERSIONS</text>${label(0,angle,'GC Club',d.gc,'white')}${label(angle,Math.PI*2,'AGA',d.aga,'#173d66')}</svg></div>`,trialDataDisclosure(['Conversion destination','Conversions','Share'],[['GC Club Conversions',fmt(d.gc),pct(d.gc/total)],['AGA Conversions',fmt(d.aga),pct(d.aga/total)],['Unresolved Conversions*',fmt(d.unresolved),'—']],`${d.month}. Percentages use ${fmt(total)} single-club matches in these two buckets. GC clubs use the existing club ID mapping; AGA conversions are non-GC clubs belonging to an AGA, so buckets do not overlap. Excluded: ${fmt(d.nonAga)} matched non-AGA/non-GC conversions and ${fmt(d.unresolved)} unresolved conversions (${fmt(d.noMatch)} without a same-day match; ${fmt(d.multipleMatches)} with multiple matches). All ${fmt(total+d.nonAga+d.unresolved)} conversions reconcile to the January–September monthly export. Attribution is based on membership creation on the conversion date, not a verified conversion-event destination. Extracted October 2, 2026.`));
}
function ghinTrials(){
 const sum=a=>a.reduce((n,v)=>n+v,0),totalCreated=sum(GHIN_LIVE_DATA.cohorts.map(r=>r.trials_created)),totalConverted=sum(GHIN_LIVE_DATA.cohorts.map(r=>r.recorded_conversions));
 const bands=[['First day','same_day'],['Next day','next_day'],['2–7 days','days_2_to_7'],['8–30 days','days_8_to_30'],['Beyond 30 days','days_31_plus']].map(([label,key])=>({label,count:sum(GHIN_LIVE_DATA.cohorts.map(r=>r[key]))})),bandTotal=sum(bands.map(r=>r.count)),largest=Math.max(...bands.map(r=>r.count));
 const kpis=[...trialHighlightValues(),['ALL ACTIVE TRIAL GOLFERS',fmt(GHIN_LIVE_DATA.trialSnapshot.active_trial_golfers),'Current pool · Oct 2'],['ALL INACTIVE TRIAL GOLFERS',fmt(GHIN_LIVE_DATA.trialSnapshot.inactive_trial_golfers),'Current pool · Oct 2']];
 return `<div class="ghin-page live-ghin-page trial-snapshot-page"><div class="trial-summary-kpis">${kpis.map(([label,value,sub])=>`<div><span>${label}</span><strong>${value}</strong><small>${sub}</small></div>`).join('')}</div><div class="live-ghin-layout">${trialMetricCard('created')}${trialMetricCard('converted')}${trialMetricCard('rate')}${trialPanel('All-Time Conversions by Days in Trial',`<div class="trial-timing-bars">${bands.map(r=>`<div class="trial-timing-row"><span>${r.label}</span><div class="trial-timing-track"><i style="width:${100*r.count/largest}%"></i></div><strong>${fmt(r.count)}</strong><span>${pct(r.count/bandTotal)}</span></div>`).join('')}</div>`,trialDataDisclosure(['Days in trial','Conversions','Share'],bands.map(r=>[r.label,fmt(r.count),pct(r.count/bandTotal)]),'All recorded conversions across available cohorts through October 2, 2026. Days are calendar days from trial_start_date to sign_up_date. Bands are mutually exclusive. The exported trial start differs from record creation for 28.3% of records; timing uses the recorded start date and may reflect date changes. No invalid or missing conversion lags were found.'))}${trialDestinationPie()}</div></div>`;
}
function liveGhinHistoryTable(kind,contentOnly=false){const trial=kind==='trials',records=trial?GHIN_LIVE_DATA.trials:GHIN_LIVE_DATA.gps;const html=`<details class="chart-data-disclosure live-ghin-history"><summary><span class="chart-data-show">Show full history</span><span class="chart-data-hide">Hide full history</span></summary><div class="chart-data-table-wrap"><table><thead><tr><th>Month</th><th>${trial?'Event':'Source Status'}</th><th>Records</th><th>Distinct Golfers Within Row</th></tr></thead><tbody>${records.map(r=>`<tr><th>${(r.event_month||r.activity_month).slice(0,7)}${(r.event_month||r.activity_month).startsWith('2026-10')?' (partial)':''}</th><td>${esc(r.event_type||r.activity_status)}</td><td>${fmt(r.trial_records??r.activity_records)}</td><td>${fmt(r.unique_golfers)}</td></tr>`).join('')}</tbody></table></div><p class="live-source-note">Full aggregate export through October 2, 2026. Distinct golfers cannot be summed across months or statuses without deduplication. October is partial. GPS records may reflect later status updates.</p></details>`;return contentOnly?html.replace(/^<details[^>]*><summary>[\s\S]*?<\/summary>/,'').replace(/<\/details>$/,''):html;}
const gpsTrendYears={new:new Set([2024,2025,2026]),renewed:new Set([2024,2025,2026]),canceled:new Set([2024,2025,2026]),expired:new Set([2024,2025,2026])};
function toggleGpsTrendYear(kind,year){const years=gpsTrendYears[kind];years.has(year)?years.delete(year):years.add(year);render();}
function gpsTrendRows(){const months=[...new Set(GHIN_LIVE_DATA.gps.map(r=>r.activity_month))].filter(m=>m>='2024-01-01'&&m<'2026-10-01').sort();return months.map(month=>({month,year:+month.slice(0,4),index:+month.slice(5,7)-1,newCount:liveGhinValue('gps','new',month),renewed:liveGhinValue('gps','renewed',month)})).map(r=>({...r,total:r.newCount+r.renewed}));}
function showGpsTrendTooltip(el){const box=el.closest('.gps-trend-chart'),tip=box.querySelector('.trial-rate-tooltip');tip.innerHTML=`<strong>${el.dataset.period}</strong><div>${el.dataset.metric} <b>${el.dataset.total}</b></div>`;tip.hidden=false;const p=el.getBoundingClientRect(),b=box.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(p.x-b.x-105,b.width-226))+'px';tip.style.top=Math.max(8,p.y-b.y-130)+'px';}
function hideGpsTrendTooltip(el){el.closest('.gps-trend-chart').querySelector('.trial-rate-tooltip').hidden=true;}
const gpsTrendModes={new:'ytd',renewed:'ytd',canceled:'ytd',expired:'ytd'};
function setGpsTrendMode(kind,mode){gpsTrendModes[kind]=mode;render();}
function gpsActivityTrend(kind){
 const mode=gpsTrendModes[kind],title={new:'New GPS Subscribers by Year',renewed:'GPS Renewals by Year',canceled:'GPS Cancellations',expired:'GPS Expirations'}[kind],metric={new:'New Subscribers',renewed:'Renewals',canceled:'Cancellations',expired:'Expirations'}[kind],selected=gpsTrendYears[kind],years=[2024,2025,2026],colors=['#8496ad','#5585ad','#173d66'],months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
 const rows=gpsTrendRows().map(v=>({...v,total:liveGhinValue('gps',kind,v.month),period:`${months[v.index]} ${v.year}`}));
 const annual=years.map((year,i)=>{const records=rows.filter(v=>v.year===year&&(mode!=='ytd'||v.index<9));return {year,total:records.reduce((n,v)=>n+v.total,0),period:mode==='ytd'?'Jan–Sep':year===2026?'Jan–Sep YTD':'Full year',color:colors[i],complete:records.length===(mode==='ytd'?9:12)};});
 const data=mode==='monthly'?rows:annual,w=650,h=350,l=58,r=25,t=25,b=50,ceiling=Math.max(1,...data.map(v=>v.total))*1.25,x=i=>l+i*(w-l-r)/11,y=n=>h-b-n/ceiling*(h-t-b),events=v=>`class="trial-rate-point" tabindex="0" role="button" aria-label="${v.period}: ${fmt(v.total)} ${metric}" data-period="${mode==='monthly'?v.period:`${v.year} · ${v.period}`}" data-metric="${metric}" data-total="${fmt(v.total)}" onpointerenter="showGpsTrendTooltip(this)" onpointerleave="hideGpsTrendTooltip(this)" onfocus="showGpsTrendTooltip(this)" onblur="hideGpsTrendTooltip(this)" onclick="showGpsTrendTooltip(this)" onkeydown="if(event.key==='Escape')hideGpsTrendTooltip(this)"`;
 let svg=Array.from({length:5},(_,i)=>{const n=ceiling*i/4;return `<line class="gridline" x1="${l}" x2="${w-r}" y1="${y(n)}" y2="${y(n)}"/><text class="axis-label" x="${l-10}" y="${y(n)+4}" text-anchor="end">${['canceled','expired'].includes(kind)?fmt(n):short(n)}</text>`;}).join('');
 if(mode==='monthly'){
  svg+=months.map((name,i)=>`<text class="axis-label" x="${x(i)}" y="${h-b+28}" text-anchor="middle">${name}</text>`).join('');
  years.forEach((year,i)=>{if(!selected.has(year))return;const points=rows.filter(v=>v.year===year);svg+=`<g data-gps-series="${year}"><polyline fill="none" stroke="${colors[i]}" stroke-width="${year===2026?3.5:2.5}" points="${points.map(v=>`${x(v.index)},${y(v.total)}`).join(' ')}"/>${points.map(v=>`<g ${events(v)}><circle cx="${x(v.index)}" cy="${y(v.total)}" r="12" fill="transparent"/><circle cx="${x(v.index)}" cy="${y(v.total)}" r="5" fill="white" stroke="${colors[i]}" stroke-width="2" pointer-events="none"/></g>`).join('')}</g>`;});
 }else{
  annual.forEach((v,i)=>{const center=l+(i+.5)*(w-l-r)/3;svg+=`<text class="axis-label" x="${center}" y="${h-b+23}" text-anchor="middle">${v.year}</text><text class="axis-label" x="${center}" y="${h-b+42}" text-anchor="middle">${v.period}</text>`;if(!selected.has(v.year))return;const prior=annual[i-1],delta=prior?.total&&prior.complete&&v.complete?(v.total/prior.total-1)*100:null;svg+=`<g ${events(v)}><rect data-gps-bar="${v.year}" x="${center-48}" y="${y(v.total)}" width="96" height="${h-b-y(v.total)}" rx="5" fill="${v.color}"/><text class="trial-chart-value" x="${center}" y="${y(v.total)-12}" text-anchor="middle">${fmt(v.total)}</text>${delta===null?'':`<text class="trial-change-label" x="${center}" y="${y(v.total)-32}" text-anchor="middle" fill="${(['canceled','expired'].includes(kind)?delta<=0:delta>=0)?'#07853b':'#c5232c'}">${delta>=0?'▲':'▼'} ${Math.abs(delta).toFixed(1)}%</text>`}</g>`;});
 }
 if(!selected.size)svg+=`<text class="axis-label" x="${w/2}" y="${h/2}" text-anchor="middle">Select a year to show its data.</text>`;
 const legend=`<div class="trial-rate-years" role="group" aria-label="Show or hide ${title} years">${years.map((year,i)=>`<button type="button" aria-pressed="${selected.has(year)}" onclick="toggleGpsTrendYear('${kind}',${year})"><i style="background:${colors[i]}"></i>${year}</button>`).join('')}</div>`;
 return trialPanel(`${title} <span class="trial-year-toggle" role="group" aria-label="${title} chart view">${[['ytd','YTD'],['annual','Annual Totals'],['monthly','Monthly']].map(([value,label])=>`<button type="button" data-gps-mode="${kind}-${value}" aria-pressed="${mode===value}" onclick="setGpsTrendMode('${kind}','${value}')">${label}</button>`).join('')}</span>`,`<div class="live-ghin-chart trial-rate-chart gps-trend-chart"><div class="trial-rate-tooltip" role="tooltip" hidden></div><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${title} · ${mode}">${svg}</svg>${legend}</div>`,trialDataDisclosure(['Period',metric],data.filter(v=>selected.has(v.year)).map(v=>[mode==='monthly'?v.period:`${v.year} · ${v.period}`,fmt(v.total)]),`Counts use gps_activities records labeled ${kind}, grouped by creation month. These are record counts, not deduplicated subscribers or historical active-subscriber totals. Statuses may be updated after creation. YTD compares January–September for each year. Annual Totals shows full-year 2024 and 2025, and January–September 2026. Changes appear only between complete, matching periods. October 2026 is partial and excluded. Extracted October 2, 2026.`)).replace('class="card live-ghin-product trial-detail-card"',`class="card live-ghin-product trial-detail-card" data-gps-kind="${kind}"`);
}

function advancedGps(){
 const d=GHIN_LIVE_DATA.gpsSnapshot,rows=gpsTrendRows(),sum=(year,key)=>rows.filter(r=>r.year===year&&r.index<9).reduce((n,r)=>n+r[key],0),newTotal=sum(2026,'newCount'),renewalTotal=sum(2026,'renewed'),change=(value,base)=>base?`${value>=base?'▲':'▼'} ${Math.abs((value/base-1)*100).toFixed(1)}% vs 2025 YTD`:'—',lifetime=GHIN_LIVE_DATA.gps.filter(r=>['new','renewed'].includes(r.activity_status)).reduce((n,r)=>n+r.activity_records,0);
 const highlights=[['Current Subscribers',fmt(d.activeFlagged),'Snapshot · October 2, 2026'],['2026 New Subscribers YTD',fmt(newTotal),change(newTotal,sum(2025,'newCount'))],['2026 Renewals YTD',fmt(renewalTotal),change(renewalTotal,sum(2025,'renewed'))],['Lifetime New + Renewals*',fmt(lifetime),'Transactions · through October 2, 2026']];
 const septemberHighlights=[['new','September New Subscribers'],['renewed','September Renewals'],['canceled','September Cancellations'],['expired','September Expirations']].map(([key,label])=>{const value=liveGhinValue('gps',key,'2026-09-01'),prior=liveGhinValue('gps',key,'2025-09-01'),delta=prior?(value/prior-1)*100:null,good=delta!==null&&(['canceled','expired'].includes(key)?delta<0:delta>0),color=delta===0||delta===null?'#64748b':good?'#07853b':'#c5232c',comparison=delta===null?(value?'New · 0 in Sept 2025':'No change · 0 in Sept 2025'):`${delta>0?'▲':delta<0?'▼':'•'} ${Math.abs(delta).toFixed(1)}% vs Sept 2025`;return `<div><span>${label}</span><strong>${fmt(value)}</strong><small style="color:${color};font-weight:700">${comparison}</small></div>`;}).join('');

 return `<div class="ghin-page live-ghin-page"><div class="trial-summary-kpis gps-current-kpis">${highlights.map(([label,value,note],i)=>`<div><span>${label}</span><strong>${value}</strong><small${i===1||i===2?` style="color:${note.startsWith('▼')?'#c5232c':'#07853b'};font-weight:700"`:''}>${note}</small></div>`).join('')}</div><div class="trial-summary-kpis gps-current-kpis gps-september-kpis" aria-label="September 2026 highlights">${septemberHighlights}</div><div class="live-ghin-layout gps-trend-layout">${gpsActivityTrend('new')}${gpsActivityTrend('renewed')}${gpsLifecycleTiles()}</div>${trialDataDisclosure(['Highlight','Definition'],[['Current Subscribers','Unique golfers with a subscription flagged active on October 2, 2026.'],['2026 YTD','January–September; year-over-year changes use the same months in 2025.'],['Lifetime New + Renewals*','Sum of new and renewed records across the available exported history, including partial October 2026. Counts transactions as a working measure, not unique golfers.']], '* Lifetime is limited to retained records in this export; complete lifetime coverage has not been established. New and renewal statuses are used as transaction measures; successful payment has not been verified for each record.').replace(/<\/details>$/,liveGhinHistoryTable('gps',true)+'</details>').replace('chart-data-disclosure live-ghin-data trial-clean-data','chart-data-disclosure live-ghin-data trial-clean-data gps-page-notes').replace(/<summary>[\s\S]*?<\/summary>/,'<summary>Data &amp; notes</summary>')}</div>`;
}

function ghinTotals(){return `<div class="ghin-page"><div class="grid ghin-totals-grid">${summaryGpsCard()}${summaryTrialsCard()}${ghinTotalsChallengeCard('TOTAL GHIN CHALLENGES','769','173.7','281','769')}${ghinTotalsChallengeCard('GHIN CHALLENGE GOLFERS','30,559','275.6','8','31','K')}</div></div>`;}

function gpsLifecycleTiles(){
 return gpsActivityTrend('canceled')+gpsActivityTrend('expired')+gpsTenureTile();
}

function gpsTenureTile(){
 const rows=GHIN_LIVE_DATA.gpsTenure.rows,active=rows.find(r=>r.cohort==='Active-flagged'),canceled=rows.find(r=>r.cohort==='Latest record canceled'),expired=rows.find(r=>r.cohort==='Latest record expired'),groups=[['Active',active,'Through October 4'],['Canceled',canceled,'Through scheduled end'],['Expired',expired,'Through end date']],excluded=r=>((+r.missing_date_golfers + +r.invalid_date_golfers)/+r.unique_golfers*100).toFixed(1);
 const bands=[['Under 1 year','under_1_year','#173d66'],['1–2 years','from_1_to_under_2_years','#5585ad'],['2–3 years','from_2_to_under_3_years','#8496ad'],['3+ years','at_least_3_years','#df572d']];
 const legend=`<span class="gps-tenure-legend">${bands.map(([label,key,color])=>`<span><i style="background:${color}"></i>${label}</span>`).join('')}</span>`;
 const body=`<div class="gps-tenure-bars">${groups.map(([label,r,basis],i)=>`<div class="gps-tenure-bar-row"><div class="gps-tenure-bar-label">${label}</div><div class="gps-tenure-track" role="img" aria-label="${label}: ${bands.map(([name,key])=>`${name} ${r[key+'_pct']} percent`).join(', ')}">${bands.map(([name,key,color])=>`<span style="width:${100*(+r[key])/(+r.valid_tenure_golfers)}%;background:${color}" title="${label} · ${name}: ${fmt(+r[key])} golfers (${r[key+'_pct']}%)">${r[key+'_pct']}%</span>`).join('')}</div><div class="gps-tenure-bar-average"><strong>${r.average_tenure_months} mo.</strong><small>average</small></div></div>`).join('')}</div>`;
 const note=`<p class="gps-tenure-footnote">Time since first subscribing · Date exclusions: ${excluded(active)}% active, ${excluded(canceled)}% canceled, ${excluded(expired)}% expired. Spans may include gaps.</p>`;
 const table=groups.map(([label,r])=>[label,fmt(+r.unique_golfers),fmt(+r.valid_tenure_golfers),`${r.average_tenure_months} / ${r.median_tenure_months}`,`${r.under_1_year_pct}%`,`${r.from_1_to_under_2_years_pct}%`,`${r.from_2_to_under_3_years_pct}%`,`${r.at_least_3_years_pct}%`]);
 return trialPanel('GPS Subscriber Tenure'+legend,`<div class="gps-tenure-body">${body}</div>`,trialDataDisclosure(['Group','Golfers','Valid dates','Avg. / median months','Under 1 year','1–2 years','2–3 years','3+ years'],table,`One golfer per cohort; cohorts overlap, including canceled subscribers still flagged active. Averages, medians and bands use only valid tenure records. Active: ${fmt(+active.valid_tenure_golfers)} valid, ${fmt(+active.missing_date_golfers)} missing and ${fmt(+active.invalid_date_golfers)} invalid. Canceled: ${fmt(+canceled.valid_tenure_golfers)} valid and ${fmt(+canceled.invalid_date_golfers)} invalid. Expired: ${fmt(+expired.valid_tenure_golfers)} valid and ${fmt(+expired.invalid_date_golfers)} invalid. Active tenure runs to October 4; canceled tenure runs to the scheduled end, which may be in the future; expired tenure runs to the end date. Canceled elapsed tenure through the extraction date averages ${canceled.average_elapsed_months_to_date} months. Cancellation timing averages ${canceled.average_months_until_cancellation} months, with a median of ${canceled.median_months_until_cancellation} months, using a separate population of ${fmt(+canceled.golfers_with_valid_cancellation_date)} golfers with valid cancellation dates. Annual access can continue after cancellation. Same-day differences between the first subscription and current-term start timestamps are allowed. Remaining expired exclusions have future end dates. Band percentages use valid-tenure golfers; year boundaries are calendar anniversaries, so a 365-day term may fall short of an anniversary across a leap day. Earliest retained initial subscription date is used; continuous access, gaps and paid renewal counts have not been established.`).replace('</summary>','</summary>'+note)).replace('class="card live-ghin-product trial-detail-card"','class="card live-ghin-product trial-detail-card gps-tenure-tile"');
}
