function summaryMembershipSnapshot(){
 const scopes=MEMBERSHIP_GEOGRAPHY_COUNTS.scopes,measures=[['Total Memberships','All Associations',scopes.all.all.memberships],['Unique Golfers','All Associations',scopes.all.all.uniqueGolfers],['Unique Golfers','AGA Only',scopes.aga.all.uniqueGolfers],['Unique Regular Golfers','AGA Only',scopes.aga.regular.uniqueGolfers],['Unique Junior Golfers','AGA Only',scopes.aga.junior.uniqueGolfers]],colors=['#a9bdd2','#809fbc','#527da5','#173d66','#6c879f'];
 return `<article class="card half home-membership-snapshot"><div class="scores-card-band has-toggle"><span>Handicapping</span><button class="trend-title-link" data-open-tab="membership" type="button">Open Membership →</button></div><div class="home-membership-body"><div class="home-score-kpis home-membership-kpis"><div><span>Unique Golfers (All Associations)</span><strong>${short(scopes.all.all.uniqueGolfers)}</strong></div><div><span>Unique Junior Golfers (All Associations)</span><strong>${short(scopes.all.junior.uniqueGolfers)}</strong></div></div><div class="home-membership-layers">${measures.map(([label,scope,count],i)=>`<div class="home-membership-layer" data-home-membership-layer="${i}" data-count="${count}"><div><span><strong>${label}</strong><small>${scope}</small></span><b>${fmt(count)}</b></div><div class="home-membership-track"><i style="width:${count/measures[0][2]*100}%;background:${colors[i]}"></i></div></div>`).join('')}</div><details class="chart-data-disclosure home-membership-data"><summary><span class="chart-data-show">Show data</span><span class="chart-data-hide">Hide data</span></summary><div class="chart-data-table-wrap"><table><thead><tr><th>Measure</th><th>Scope</th><th>Count</th></tr></thead><tbody>${measures.map(([label,scope,count])=>`<tr><th>${label}</th><td>${scope}</td><td>${fmt(count)}</td></tr>`).join('')}</tbody></table></div><p class="home-snapshot-period">Active memberships · ${esc(MEMBERSHIP_GEOGRAPHY_COUNTS.dates.all)}</p><p class="home-membership-note">Memberships count club enrollments. Unique golfers count each person once within the stated scope. Regular is a membership classification.</p></details></div></article>`;
}
function summaryScoresSnapshot(){
 const data=liveScoreData('all','all'),d=liveScoreSummary(data),card=liveScoresAnnualTotals(data,true,'bars'),chart=card.slice(card.indexOf('<div class="scores-annual-total-chart">'),card.lastIndexOf('</article>'));
 return `<article class="card half home-scores-snapshot scores-annual-totals"><div class="scores-card-band has-toggle"><span>Score Posting</span><button class="trend-title-link" data-open-tab="scores" type="button">Open Scores →</button></div><div class="home-score-kpis"><div><span>YTD Scores Posted</span><strong>${short(d.total)}</strong></div><div><span>Year-over-Year Change</span><strong class="${scoreChangeClass(d.yoy)}">${scoreChangeText(d.yoy)}</strong></div></div>${chart.replace('</details>','<p class="home-score-note">All Associations · January–August each year · Trials included</p></details>')}</article>`;
}
function summaryTopline(){
 const gc=__HOME_GC_HIGHLIGHT__;
 const scores=liveScoreSummary(liveScoreData('all','all')),conversions=year=>GHIN_LIVE_DATA.trials.filter(r=>r.event_type==='Sign-up recorded'&&r.event_month>=`${year}-01-01`&&r.event_month<`${year}-10-01`).reduce((n,r)=>n+r.trial_records,0),converted=conversions(2026),priorConverted=conversions(2025);
 const cards=[{label:'Unique Golfers',value:MEMBERSHIP_GEOGRAPHY_COUNTS.scopes.all.all.uniqueGolfers,change:null,period:'All Associations · Sept 21–25, 2026'},{label:'YTD Scores Posted',value:scores.total,change:scores.yoy,period:'All Associations · Jan–Aug 2026',basis:'vs Jan–Aug 2025'},{label:'Current GPS Subscribers',value:GHIN_LIVE_DATA.gpsSnapshot.activeFlagged,change:null,period:'Snapshot · October 2, 2026'},{label:'YTD Trial Conversions',value:converted,change:priorConverted?(converted/priorConverted-1)*100:null,period:'Jan–Sep 2026',basis:'vs Jan–Sep 2025'},{label:'GC Members',value:gc.current,change:gc.prior?(gc.current/gc.prior-1)*100:null,period:gc.period,basis:gc.basis}];
 return `<section class="home-topline home-topline-signals" aria-label="Dashboard highlights">${cards.map(c=>`<article class="home-topline-card"><span class="home-topline-label">${c.label}</span><strong class="home-topline-value">${fmt(c.value)}</strong><div class="home-topline-signal ${c.change===null?'unavailable':c.change<0?'negative':'positive'}"${c.change===null?' title="A comparable prior-year snapshot is not available."':''}>${c.change===null?'<span>YoY unavailable</span>':`<strong>${c.change>0?'▲':c.change<0?'▼':'•'} ${Math.abs(c.change).toFixed(1)}%</strong><small>${c.basis}</small>`}</div><small class="home-topline-period">${c.period}</small></article>`).join('')}</section>`;
}
function summary(){return `<div class="grid summary-home"><h2 class="home-performance-heading home-glance-heading">At a Glance</h2>${summaryTopline()}<h2 class="home-performance-heading">Performance Overview</h2>${summaryMembershipSnapshot()}${summaryScoresSnapshot()}${summaryGpsCard()} ${summaryTrialConversionsCard()}</div>`;}
