let membershipAssociationRegion='all';
function liveMembershipAssociations(){
  const source=MEMBERSHIP_ASSOCIATION_DATA.scopes[membershipGeography][membershipPopulation],rows=source.filter(r=>membershipAssociationRegion==='all'||r.region===membershipAssociationRegion).filter(r=>associationHcpRange==='ALL'||associationHcpRange==='0-49999'&&r.activeGolfers<50000||associationHcpRange==='50000-99999'&&r.activeGolfers>=50000&&r.activeGolfers<100000||associationHcpRange==='100000-199999'&&r.activeGolfers>=100000&&r.activeGolfers<200000||associationHcpRange==='200000+'&&r.activeGolfers>=200000).map(r=>({...r}));
  const available=['name','activeGolfers','memberships','gcMemberships','femalePct','averageAge','publicMembersPct','gcClubMembersPct','clubCount','publicClubsPct','type2ClubsPct'],key=available.includes(rankSort.key)?rankSort.key:'activeGolfers',dir=rankSort.direction==='asc'?1:-1;
  rows.sort((a,b)=>{const x=a[key],y=b[key];if(x==null||y==null)return x==null?(y==null?0:1):-1;return (typeof x==='string'?x.localeCompare(y):x-y)*dir||a.name.localeCompare(b.name);});
  const header=(key,label,extra='')=>`<th ${extra}><button type="button" data-membership-association-sort="${key}">${label} <span>${rankSort.key===key?(dir===1?'▲':'▼'):'↕'}</span></button></th>`;
  const percentage=v=>v==null?'—':pct(v);
  return `<section class="association-landscape membership-association-live"><div class="association-page-head"><div class="membership-association-filters"><label class="association-range-control"><span>Region</span><select aria-label="Association region" onchange="membershipAssociationRegion=this.value;render()">${['all','West','Central','Midwest','Northeast','Southeast','International'].map(region=>`<option value="${region}"${membershipAssociationRegion===region?' selected':''}>${region==='all'?'All Regions':region}</option>`).join('')}</select></label><label class="association-range-control"><span>Association Size (Unique Golfers)</span><select id="associationHcpRange">${[['ALL','All Sizes'],['0-49999','0–49,999'],['50000-99999','50,000–99,999'],['100000-199999','100,000–199,999'],['200000+','200,000+']].map(([v,label])=>`<option value="${v}"${associationHcpRange===v?' selected':''}>${label}</option>`).join('')}</select></label></div></div><div class="table-wrap"><table class="rank-table membership-association-table"><thead><tr><th rowspan="2">Rank</th>${header('name','Association','rowspan="2"')}<th colspan="6" class="ma-totals">Active Totals</th><th colspan="3" class="ma-profile">Member Profile</th><th colspan="3" class="ma-clubs">Golf Clubs</th></tr><tr>${header('activeGolfers','Unique Golfers')}${header('memberships','Memberships')}${header('gcMemberships','GC Memberships')}${header('gcClubMembersPct','% GC Club')}<th>YoY</th><th>5-Year</th>${header('femalePct','% Female')}${header('averageAge','Avg. Age')}${header('publicMembersPct','% Public')}${header('clubCount','# of Clubs')}${header('publicClubsPct','% Public')}${header('type2ClubsPct','% Type 2')}</tr></thead><tbody>${rows.map((r,i)=>`<tr data-membership-association="${esc(r.id)}" data-association-region="${esc(r.region)}"><td>${i+1}</td><th scope="row">${esc(r.name)}</th><td data-ma-unique="${r.activeGolfers}">${fmt(r.activeGolfers)}</td><td data-ma-memberships="${r.memberships}">${fmt(r.memberships)}</td><td data-ma-gc-memberships="${r.gcMemberships}">${fmt(r.gcMemberships)}</td><td>${percentage(r.gcClubMembersPct)}</td><td data-ma-change>—</td><td data-ma-change>—</td><td>${percentage(r.femalePct)}</td><td>${r.averageAge==null?'—':r.averageAge.toFixed(1)}</td><td>${percentage(r.publicMembersPct)}</td><td>${fmt(r.clubCount)}</td><td>${percentage(r.publicClubsPct)}</td><td>${percentage(r.type2ClubsPct)}</td></tr>`).join('')||'<tr><td colspan="14">No associations match this selection.</td></tr>'}</tbody></table></div><p class="live-source-note">Unique golfers are deduplicated within each association and may belong to more than one association. Member profile percentages use active memberships; average age excludes missing or invalid ages. Golf Clubs counts clubs with active memberships in the selected population. YoY and 5-Year changes are unavailable.</p></section>`;
}
document.addEventListener('click',e=>{const button=e.target.closest('[data-membership-association-sort]');if(!button)return;const key=button.dataset.membershipAssociationSort;rankSort={key,direction:rankSort.key===key?(rankSort.direction==='desc'?'asc':'desc'):key==='name'?'asc':'desc'};render();});
