function defaultMembershipClubFilters(){return {association:{mode:'include',values:[]},access:{mode:'include',values:[]},type:{mode:'include',values:[]},category:{mode:'include',values:[]},juniors:{mode:'include',values:[]},search:''};}
let membershipClubFilters=defaultMembershipClubFilters(),membershipClubSort={key:'members',direction:'desc'},membershipClubPage=0;
function setMembershipClubFilter(key,value){membershipClubFilters[key]=value;membershipClubPage=0;render();}
function updateMembershipClubChecklist(key,action,value,element){
 const panel=element.closest('details'),scroll=panel.querySelector('.club-filter-options').scrollTop,focus=element.dataset.clubFilterFocus,f=membershipClubFilters[key];
 if(action==='mode')f.mode=value;
 else if(action==='clear')f.values=[];
 else f.values=f.values.includes(value)?f.values.filter(v=>v!==value):[...f.values,value];
 membershipClubPage=0;render();
 const next=document.getElementById('club-filter-'+key);next.open=true;next.querySelector('.club-filter-options').scrollTop=scroll;
 next.querySelector(`[data-club-filter-focus="${focus}"]`)?.focus({preventScroll:true});
}
function membershipClubFilterMatches(filter,value){return !filter.values.length||(filter.mode==='exclude'?!filter.values.includes(value):filter.values.includes(value));}
document.addEventListener('click',event=>{if(!event.target.isConnected)return;document.querySelectorAll('.club-filter-dropdown[open]').forEach(panel=>{if(!panel.contains(event.target))panel.open=false;});});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){const panel=event.target.closest('.club-filter-dropdown');if(panel){panel.open=false;panel.querySelector('summary').focus();}}});
function sortMembershipClubs(key){membershipClubSort={key,direction:membershipClubSort.key===key?(membershipClubSort.direction==='asc'?'desc':'asc'):(['members','juniorPct'].includes(key)?'desc':'asc')};membershipClubPage=0;render();}
function membershipClubRows(){
 const base=MEMBERSHIP_CLUB_DATA.clubs.filter(r=>(membershipGeography==='all'||r.scope===membershipGeography)&&r[membershipPopulation]>0);
 const associations=[...new Map(base.map(r=>[r.association,r.associationName])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
 const available={association:associations.map(([id])=>id),access:base.map(r=>r.access),type:base.map(r=>r.type),category:base.map(r=>r.category)};
 for(const key of Object.keys(available))membershipClubFilters[key].values=membershipClubFilters[key].values.filter(v=>available[key].includes(v));
 const f=membershipClubFilters,query=f.search.trim().toLowerCase();
 const rows=base.filter(r=>['association','access','type','category'].every(key=>membershipClubFilterMatches(f[key],r[key]))&&(!f.juniors.values.length||(f.juniors.mode==='exclude'?!f.juniors.values.some(v=>r.junior*100>=Number(v)*r.all):f.juniors.values.some(v=>r.junior*100>=Number(v)*r.all)))&&(!query||[r.name,r.id,r.associationName].some(v=>v.toLowerCase().includes(query)))).map(r=>({...r,members:r[membershipPopulation],juniorPct:r.all?r.junior/r.all:0}));
 const {key,direction}=membershipClubSort;
 rows.sort((a,b)=>{const cmp=['members','juniorPct'].includes(key)?a[key]-b[key]:String(a[key]).localeCompare(String(b[key]),undefined,{numeric:true});return (direction==='asc'?cmp:-cmp)||a.name.localeCompare(b.name)||a.id.localeCompare(b.id);});
 return {base,associations,rows};
}
function membershipClubs(){
 const {base,associations,rows}=membershipClubRows(),pageSize=100,pages=Math.max(1,Math.ceil(rows.length/pageSize));membershipClubPage=Math.min(membershipClubPage,pages-1);
 const start=membershipClubPage*pageSize,visible=rows.slice(start,start+pageSize),f=membershipClubFilters;
 const checklist=(key,label,allLabel,options)=>{
  const filter=f[key],names=options.filter(([id])=>filter.values.includes(id)).map(([,name])=>name),summary=names.length?`${filter.mode==='include'?'Include':'Exclude'}: ${names.join(', ')}`:allLabel;
  return `<div class="club-filter-field"><span class="club-filter-label" id="club-filter-label-${key}">${label}</span><details class="club-filter-dropdown" id="club-filter-${key}"><summary aria-labelledby="club-filter-label-${key} club-filter-summary-${key}" title="${esc(summary)}"><span id="club-filter-summary-${key}">${esc(summary)}</span></summary><div class="club-filter-panel"><div class="club-filter-mode" role="group" aria-label="${label} filter mode">${['include','exclude'].map(mode=>`<button type="button" aria-pressed="${filter.mode===mode}" data-club-filter-focus="${mode}" onclick="updateMembershipClubChecklist('${key}','mode','${mode}',this)">${mode==='include'?'Include':'Exclude'}</button>`).join('')}</div><div class="club-filter-options">${options.map(([id,name],i)=>`<label><input type="checkbox" value="${esc(id)}" data-club-filter-focus="option-${i}" ${filter.values.includes(id)?'checked':''} onchange="updateMembershipClubChecklist('${key}','value',this.value,this)"><span>${esc(name)}</span></label>`).join('')}</div><div class="club-filter-footer"><span>No selections = all clubs</span><button type="button" data-club-filter-focus="clear" onclick="updateMembershipClubChecklist('${key}','clear','',this)">Clear</button></div></div></details></div>`;
 };
 const columns=[['name','Club'],['id','Club ID'],['associationName','Association'],['members','Members'],['juniorPct','% Junior'],['access','Public / Private'],['type','Club Type'],['category','Club Category']];
 const pagination=()=>`<div class="membership-club-pagination"><span>${rows.length?`${fmt(start+1)}–${fmt(Math.min(start+pageSize,rows.length))} of ${fmt(rows.length)} clubs`:'No matching clubs'}</span><button type="button" onclick="membershipClubPage--;render()"${membershipClubPage===0?' disabled':''}>Previous</button><span>Page ${membershipClubPage+1} of ${pages}</span><button type="button" onclick="membershipClubPage++;render()"${membershipClubPage>=pages-1?' disabled':''}>Next</button></div>`;
 return `<section class="membership-club-view" aria-label="Clubs"><div class="membership-club-filters">${checklist('association','Association','All Associations',associations)}${checklist('access','Public / Private','All Access',[['Public','Public'],['Private','Private'],['Unknown','Unknown']])}${checklist('type','Club Type','All Types',[...new Set(base.map(r=>r.type))].sort().map(t=>[t,t]))}${checklist('category','Club Category','All Categories',[...new Set(base.map(r=>r.category))].sort().map(t=>[t,t]))}${checklist('juniors','Juniors','All Clubs',[['30','30% or More Juniors'],['50','50% or More Juniors'],['75','75% or More Juniors'],['100','100% Juniors']])}<label>Search clubs<input type="search" aria-label="Search clubs" placeholder="Club name or ID" value="${esc(f.search)}" onchange="setMembershipClubFilter('search',this.value)"></label><button type="button" class="membership-club-reset" onclick="membershipClubFilters=defaultMembershipClubFilters();membershipClubPage=0;render()">Reset filters</button></div><div class="membership-club-summary"><strong>${fmt(rows.length)} clubs</strong><span>${fmt(rows.reduce((n,r)=>n+r.members,0))} active memberships · ${membershipPopulationLabel()}</span></div><div class="membership-club-table-wrap"><table class="membership-club-table"><thead><tr>${columns.map(([key,label])=>`<th aria-sort="${membershipClubSort.key===key?(membershipClubSort.direction==='asc'?'ascending':'descending'):'none'}"><button type="button" data-membership-club-sort="${key}" onclick="sortMembershipClubs('${key}')">${label} ${membershipClubSort.key===key?(membershipClubSort.direction==='asc'?'▲':'▼'):'↕'}</button></th>`).join('')}</tr></thead><tbody>${visible.map(r=>`<tr data-club-id="${esc(r.id)}"><th scope="row">${esc(r.name)}</th><td>${esc(r.id)}</td><td>${esc(r.associationName)}</td><td class="member-count" data-club-members="${r.members}">${fmt(r.members)}</td><td class="member-count">${pct(r.juniorPct)}</td><td>${esc(r.access)}</td><td>${esc(r.type)}</td><td>${esc(r.category)}</td></tr>`).join('')||'<tr><td colspan="8">No clubs match these filters.</td></tr>'}</tbody></table></div>${pagination()}<p class="live-source-note">Clubs with active memberships in the selected group · ${membershipScopeDate()}. % Junior is junior memberships divided by all memberships at each club, regardless of the selected member filter. Counts are memberships; golfers belonging to multiple clubs count in each club. GC clubs are identified separately from their recorded Type 1/2/3 classification. Public includes semi-private, resort, municipal, military, affiliate and virtual clubs. Clubs with no active memberships are not present in these exports.</p></section>`;
}
