function membershipDummyMark(){return '';}
let membershipTrendMeasure="memberships";
const MEMBERSHIP_BILLABLE_MONTHLY={"2022":[3027944,3027944,2976029,2996462,3018442,3134090,3088747,3128325,3159137,3176348,3157955,3167398],"2023":[3200184,3200184,3159518,3175024,3193342,3183039,3157484,3197217,3225618,3242598,3256333,3265906],"2024":[3265906,3265906,3221550,3234527,3259109,3371564,3354748,3392330,3421438,3441763,3456460,3463963],"2025":[3463963,3463963,3428231,3441695,3473809,3610722,3607784,3645945,3682190,3705870,3721295,3730304],"2026":[3730304,3730304,3706308,3719765,3721780,3771576,3759241,3791721,3814564,null,null,null]};
function membershipBillableAvailable(){return membershipGeography==='all'&&membershipPopulation==='all';}
function membershipBillableMonth(year,month){return membershipBillableAvailable()?(MEMBERSHIP_BILLABLE_MONTHLY[year]?.[month]??null):null;}
const MEMBERSHIP_OFFICIAL_ANNUAL={2020:{all:2596357,regular:null,junior:null},2021:{all:2850384,regular:null,junior:null},2022:{all:3067273,regular:null,junior:null},2023:{all:3191080,regular:2978607,junior:212473},2024:{all:3396673,regular:3130056,junior:266617},2025:{all:3615512,regular:3222848,junior:392664}};
let membershipGeography="aga";
const MEMBERSHIP_GEOGRAPHY_COUNTS=null;
const MEMBERSHIP_GEOGRAPHY_COMPOSITION=null;
function scopedCompositionData(pop){return membershipGeography==="aga"?MEMBERSHIP_COMPOSITION_DATA[pop]:MEMBERSHIP_GEOGRAPHY_COMPOSITION[membershipGeography][pop];}
function membershipScopeDate(){return MEMBERSHIP_GEOGRAPHY_COUNTS.dates[membershipGeography];}
function membershipScopeLabel(){return {aga:'AGA Only',international:'International Only',all:'All Associations'}[membershipGeography];}
function membershipScopeControl(){return `<label class="membership-scope-control"><select aria-label="Association scope" onchange="membershipGeography=this.value;render()">${[['aga','AGA Only'],['international','International Only'],['all','All Associations']].map(([key,label])=>`<option value="${key}" ${membershipGeography===key?'selected':''}>${label}</option>`).join('')}</select></label>`;}
function membershipScopeData(d){if(membershipGeography==='aga')return d;const counts=MEMBERSHIP_GEOGRAPHY_COUNTS.scopes[membershipGeography][membershipPopulation],current=counts[d.unique?'uniqueGolfers':'memberships'];return {...d,annual:d.years.map(y=>y===2026?current:null),current};}
function membershipScopeNotice(){return `<div class="membership-scope-notice"><strong>${membershipScopeLabel()}</strong><span>Active membership extract · ${membershipScopeDate()}${membershipGeography==='all'?' · Unique golfers deduplicated across scopes':''}</span></div>`;}
function membershipTotalsData(){const unique=membershipTrendMeasure==='unique',label=membershipPopulation==='all'?'All Members':membershipPopulation==='regular'?'Regular Members':'Junior Members';if(!unique){const years=[2022,2023,2024,2025,2026];return {label,years,annual:years.map(y=>membershipBillableMonth(y,y===2026?8:11)),current:membershipBillableMonth(2026,8),unique:false};}const current=MEMBERSHIP_COMPOSITION_DATA[membershipPopulation].counts.uniqueGolfers,years=[2020,2021,2022,2023,2024,2025,2026];return membershipScopeData({label,years,annual:years.map(y=>y===2026?current:MEMBERSHIP_OFFICIAL_ANNUAL[y][membershipPopulation]),current,unique});}
function membershipBillableSource(){return 'Source: Matthew Cogliandro · Golfer Subscription Tracker. Historical counts use billing records over the preceding 12 billing months, generally counting each golfer once per association. Golfers in different associations count separately. These are not point-in-time active membership counts. Available for All Associations / All Members only.';}

function membershipTotalsValue(value){return value==null?'no data':fmt(value);}
function membershipTotalsChange(current,prior){return current==null||prior==null||prior===0?null:(current/prior-1)*100;}
function membershipTotalsKpi(label,value,period,change=false){const missing=value==null,tone=!missing&&change?(value>=0?'positive':'negative'):'';return `<div class="performance-block"><div class="performance-label">${label}</div><div class="performance-value ${change?tone:'report-value'}">${missing?'no data':change?`${value>=0?'▲':'▼'} ${Math.abs(value).toFixed(1)}%`:fmt(value)}</div><div class="performance-period">${period}</div></div>`;}
function membershipMarkedBars(values,growth,labels){let markup=membershipBarChart(values.map(v=>v??0),growth.map(v=>v??0),labels),i=0;markup=markup.replace(/(<text[^>]*class="membership-bar-total[^>]*>)([^<]*)(<\/text>)/g,(m,a,b,c)=>{const v=values[i++];return a+(v==null?'no data':b)+c});i=0;markup=markup.replace(/(<text[^>]*class="membership-growth-text[^>]*>)([^<]*)(<\/text>)/g,(m,a,b,c)=>a+(growth[i++]==null?'no data':b)+c);i=0;markup=markup.replace(/(<rect class="membership-bar acq-bar [^>]+)\/>/g,(m,a)=>{const v=values[i],label=labels[i++];return v==null?'':a+`><title>${label}: ${fmt(v)}</title></rect>`});return markup.replace('Membership annual bar chart',membershipTrendMeasure==='unique'?'Unique golfers annual bar chart':'Membership annual bar chart');}
function membershipTrendDataDisclosure(labels,values,growth,note){return `<details class="chart-data-disclosure"><summary><span class="chart-data-show">Show data</span><span class="chart-data-hide">Hide data</span></summary><div class="chart-data-table-wrap"><table><thead><tr><th>Period</th><th>Count</th><th>Change vs. previous period shown</th></tr></thead><tbody>${labels.map((label,i)=>`<tr><th>${esc(label)}</th><td>${membershipTotalsValue(values[i])}</td><td>${growth[i]==null?'no data':`${growth[i]>=0?'+':''}${growth[i].toFixed(1)}%`}</td></tr>`).join('')}</tbody></table></div><p class="membership-trend-source">${note}</p></details>`;}
function membershipGrowthCard(){const d=membershipTotalsData(),values=d.annual,years=d.years,growth=values.map((v,i)=>i?membershipTotalsChange(v,values[i-1]):null);return `<article class="card full membership-summary-card totals-primary-chart-card membership-trend-shell"><div class="membership-trend-band"><h3>${d.unique?'Total Unique Golfer Trend':'Membership Trend'}</h3><div class="projection-controls membership-measure-toggle" role="group" aria-label="Trend measure">${[['memberships','Memberships'],['unique','Unique Golfers']].map(([key,label])=>`<button type="button" data-membership-measure="${key}" aria-pressed="${membershipTrendMeasure===key}" class="${membershipTrendMeasure===key?'active':''}" onclick="membershipTrendMeasure='${key}';render()">${label}</button>`).join('')}</div></div><div class="performance-row reporting-row membership-trend-performance">${membershipTotalsKpi('2026 '+(d.unique?'Unique Golfers':'Memberships'),d.current,d.unique?'Thru Sept · '+membershipScopeDate():'September 2026 · Matt’s reported count')}${membershipTotalsKpi('1-Year Change',membershipTotalsChange(d.current,values[years.indexOf(2025)]),d.unique?'September snapshot vs. 2025 annual count':'September 2026 vs. December 2025',true)}${membershipTotalsKpi('3-Year Change',membershipTotalsChange(d.current,values[years.indexOf(2023)]),d.unique?'September snapshot vs. 2023 annual count':'September 2026 vs. December 2023',true)}${membershipTotalsKpi('5-Year Change',membershipTotalsChange(d.current,values[years.indexOf(2021)]),d.unique?'September snapshot vs. 2021 annual count':'2021 unavailable in source',true)}</div>${membershipMarkedBars(values,growth,years.map(y=>y===2026?'2026 September':d.unique?String(y):`${y} December`))}${membershipTrendDataDisclosure(years.map(y=>y===2026?'2026 September':d.unique?String(y):`${y} December`),values,growth,`${!d.unique?membershipBillableSource():membershipGeography!=='aga'?'Historical counts for this scope: no data.':d.unique?'Steve / Central Computation supplies Total counts for 2020–2025. Junior counts for 2023–2025 are estimates; Regular = Total minus estimated Juniors. Regular and Junior breakdowns for 2020–2022: no data.':'Historical membership counts: no data.'} ${d.unique?'2026 uses current extracts; the combined scope spans September 21–25. The final bar compares a September snapshot with the prior annual count.':'Annual bars use December 2022–2025 and September 2026. For same-month comparisons, use the chart below.'}`)}</article>`;}
function membershipYoyCard(){const d=membershipTotalsData(),months=meta.months||['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],years=Array.from({length:6},(_,i)=>membershipGrowthYear-5+i),values=years.map(y=>d.unique?(y===2026&&membershipGrowthMonth===8?d.current:null):membershipBillableMonth(y,membershipGrowthMonth)),current=values.at(-1),growth=values.map((v,i)=>i?membershipTotalsChange(v,values[i-1]):null);return `<article class="card full membership-summary-card totals-primary-chart-card membership-trend-shell"><div class="membership-trend-band"><h3>Year-over-Year Trend · ${d.unique?'Unique Golfers':'Memberships'}</h3><div class="membership-selectors"><label>Month<select id="membershipGrowthMonth">${months.map((m,i)=>`<option value="${i}" ${i===membershipGrowthMonth?'selected':''}>${m}</option>`).join('')}</select></label><label>Year<select id="membershipGrowthYear">${[2020,2021,2022,2023,2024,2025,2026].map(y=>`<option value="${y}" ${y===membershipGrowthYear?'selected':''}>${y}</option>`).join('')}</select></label></div></div><div class="performance-row reporting-row membership-trend-performance">${membershipTotalsKpi(`${months[membershipGrowthMonth]} ${membershipGrowthYear} Total`,current,current==null?'Monthly count unavailable':d.unique?membershipScopeDate():'Matt’s reported monthly count')}${membershipTotalsKpi('1-Year Change',membershipTotalsChange(current,values.at(-2)),'Same month in prior year',true)}${membershipTotalsKpi('3-Year Change',membershipTotalsChange(current,values[2]),'Same month three years earlier',true)}${membershipTotalsKpi('5-Year Change',membershipTotalsChange(current,values[0]),'Same month five years earlier',true)}</div>${values.some(v=>v!=null)?membershipMarkedBars(values,growth,years.map(y=>`${months[membershipGrowthMonth]} ${y}`)):'<p class="membership-no-data">no data</p>'}${membershipTrendDataDisclosure(years.map(y=>`${months[membershipGrowthMonth]} ${y}`),values,growth,`${d.unique?'Annual counts are not monthly snapshots. Monthly history for the selected official series: no data.':membershipBillableSource()}`)}</article>`;}
function membershipProjectionCard(){return `<article class="card full membership-summary-card membership-projection-card totals-primary-chart-card"><div class="membership-card-head projection-head"><h3>2026 Year-End Projection</h3></div><p class="membership-no-data">no data</p><p class="membership-trend-source">A supported year-end projection is not available.</p></article>`;}
function membershipProjectionChart(d,rate){
  return {chart:'<p class="membership-no-data">no data</p>',target:null};
}
function membershipSummary(){const population=membershipTotalsData().label;return `<div class="membership-summary">${membershipTrendMeasure==='memberships'?`<div class="membership-scope-notice"><strong>${membershipScopeLabel()}</strong><span>Memberships · ${membershipBillableAvailable()?'Matt’s monthly series · January 2022–September 2026':'No source series supplied for this selection'}</span></div>`:membershipScopeNotice()}<div class="grid membership-summary-grid" data-population="${population}">${membershipGrowthCard()}${membershipYoyCard()}${membershipProjectionCard()}</div><p id="membership-totals-note" class="membership-dummy-note" ${membershipTrendMeasure==='memberships'?'hidden':''}>${membershipTrendMeasure==='memberships'?membershipBillableSource():`AGA source data: estimated Juniors: 2023 — 212,473; 2024 — 266,617; 2025 — 392,664. Estimates subtract international Juniors from global Juniors using the current global Junior share of 10.432149%. AGA 2026 counts come from the September 21–22 membership extract. International counts come from the September 25 extract. All Associations combines those extracts, counting each golfer ID once within the selected population. Historical International and All Associations counts: no data. Missing values are shown as “no data.”`}</p></div>`;}
